import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import Head from "next/head";
import About from "@/components/About";
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import Contact from '@/components/Contact'
import sanityClient from "@sanity/client"


export default function Home() {
  return (
  <>
    <div>
      <Head>
        <title>Frederick | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
    </>
  );
}

// export async function getServerProps() {
//   const client = sanityClient({
//     projectId: "j11vxk98",
//     dataset: "production",
//     useCdn: false,
//     apiVersion: "2023-03-29",
//   });
//   const query = `*[type == "home"]`;
//   const home = await client.fetch(query);
//   return home;
// }
